# * At least one blob storage bucket (S3, GCS, etc.), preferably two.
# * A Postgres database (RDS, Aurora, etc.). (In the future MySql support may be added.)
# * At least one IAM role for the Flyte backend service to assume. You can provision another role for user code to assume as well.

configuration:
  database:
    password: "password"
    host: "terraform-20230124034226276500000005.cffbcqn89dac.us-east-1.rds.amazonaws.com"
    dbname: flyteadmin  
  storage:
    metadataContainer: "flyte-metadata"
    userDataContainer: "flyte-user-data"
    provider: s3
    providerConfig:
      s3:
        region: "us-east-1"
        authType: "iam"
  inline:
    plugins:
      k8s:
        inject-finalizer: true
        default-env-vars:
          - AWS_METADATA_SERVICE_TIMEOUT: 5
          - AWS_METADATA_SERVICE_NUM_ATTEMPTS: 20
    storage:
      cache:
        max_size_mbs: 100
        target_gc_percent: 100
serviceAccount:
  name: "iam-role-flyte"
  create: false
